dubbo:
  #别名
  application:
    name: class-service
  #zookeeper注册地址
  registry:
    address: zookeeper://192.168.237.129:2181
  protocol:
    port: -1
    #首次启动不检查消费者
  consumer:
    check: false

#配置数据源
spring:
  datasource:
    url: jdbc:mysql://118.24.246.168:3306/class?serverTimezone=GMT%2B8
    username: student
    password: student
    driver-class-name: com.mysql.cj.jdbc.Driver
