dubbo:
  application:
    #注册名
    name: web-student-service
  registry:
    #zookeeper注册地址
    address: zookeeper://192.168.237.129:2181
  protocol:
    port: -1
    #首次启动不检查消费者
  consumer:
    check: false

spring:
  datasource:
    url: jdbc:mysql://118.24.246.168:3306/student?serverTimezone=GMT%2B8
    username: student
    password: student
    driver-class-name: com.mysql.cj.jdbc.Driver
